### ISSUE TITLE
Add more infor about Implementation, and other item

### ISSUE THREAD

**Issue by trueptolemy** [ChenPoWei/Lightning_network_resources_zh#1]
Here's more infor about lightning_network:

- Implementation:
  [rust-lightning](https://github.com/rust-bitcoin/rust-lightning)(Currently somewhere near 20% towards usable)
- Plugin for c-lightning:
  [lightningd/plugins](https://github.com/lightningd/plugins): Community curated plugins for c-lightning

Your work looks nice!

**Comment by ChenPoWei** [comment]
I'm glad you're here.
And thank you very much for your advice.
I will add your suggestion as soon as possible.
😇😇😇😇
